services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_HOST: db  
      MYSQL_PORT: 3305  # Especificamos el puerto 3305 para MariaDB
      MYSQL_USER: root
      MYSQL_PASSWORD: Epasillas0406
      MYSQL_DATABASE: transvive

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Epasillas0406
      MYSQL_DATABASE: transvive
      MYSQL_USER: root
      MYSQL_PASSWORD: Epasillas0406
    ports:
      - "3305:3306"
