services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      MYSQL_HOST: dpg-csr5lf1u0jms73cis3s0-a 
      MYSQL_PORT: 5432  # Especificamos el puerto 3305 para MariaDB
      MYSQL_USER: rmadero
      MYSQL_PASSWORD: M6WeJ17g7uV3EsuLM1Ifjnt11HHf5i6y
      MYSQL_DATABASE: transvive_piv3


