<?php
return [
    '<b>I.</b> Declara <b> "LA EMPRESA". </b>',
    '<b>a).- </b>Que es una sociedad debidamente constituida bajo la legislación mexicana vigente en el número de póliza 2,343 a cargo del Corredor Público número 2 de la Ciudad de Naucalpan, Estado de México el  Licenciado Roberto F. Ramírez Narezo, y que se encuentra debidamente registrada ante el Registro Público de Comercio.',
    '<b>b).- </b>Que cuenta con domicilio ubicado en <b>Calle. Hidalgo 30 Col. Los Gavilanes, Tlajomulco de Zúñiga, Jal.</b> Con registro federal de contribuyentes <b>TVI-190503-SA3</b>',
    '<b>c).- </b>Declara su representante que cuenta con la capacidad suficiente para contratarse y obligarse en los términos del presente instrumento, además  declara sus facultades no han sido revocadas y se encuentran vigentes, según lo dispone la escritura pública 40,781 pasada ante la fe del notario público numero102 de la Ciudad de Naucalpan, el Licenciado Horacio Aguilar Álvarez De Alba, y que se encuentra debidamente registrada ante el Registro Público del Comercio.',
    '<b>d).- OBJETO DE LA EMPRESA: </b>Contratación de personal técnico o profesional para la prestación de servicios administrativos, ejecutivos o de cualquier naturaleza para la industria, oficinas, domésticos o actividades comerciales y artísticas por cuenta propia o ajena.',
    '<b>e).- </b>Que desea contratar a una persona que cuente con los conocimientos, habilidad y experiencia necesarios para desempeñar el puesto de: <b>{cargo}</b>, y a que se refiere la primera cláusula.',
    '<b>II.- </b>Declara <b>"EL TRABAJADOR".</b>',
    '<b>a)- </b>Ser de nacionalidad mexicana, sexo <b>{sexo}</b>, estado civil: <b>{estadocivil}</b> de <b>{edad}</b> años, RFC: <b>{rfc}</b>, CURP: <b>{curp}</b>, número de Seguro social: <b>{nss}</b> con domicilio en: <b>{domicilio}</b> y tener todos los conocimientos, habilidad y experiencia necesarios para prestar a "LA EMPRESA" los servicios mencionados en el párrafo.',
    '<b>b) </b>De la Declaración I anterior. <br><br>En consideración a las declaraciones que anteceden, las partes manifiestan que es su deseo celebrar el presente contrato el cual se celebra sin actuación de dolo, mala fe, engaño por ninguna de las partes por lo que se reconocen la personalidad con la que comparecen y están de acuerdo en obligarse en virtud de las siguientes:',
    '<b>1.</b> "EL TRABAJADOR" prestará personalmente a "LA EMPRESA", los servicios descritos en la Declaración I en el puesto cuyos servicios consistirán primordialmente en todas las actividades inherentes al referido cargo, mismos que le prestará a "LA EMPRESA" o EMPRESAS a las que se le asigne y a cualquier otro tercero que le ordene "LA EMPRESA" de manera enunciativa mas no limitativa.',
    '<b>2.</b>Lo anterior lo hará bajo la dirección y dependencia de la propia EMPRESA durante la relación de trabajo. Asimismo, dada la naturaleza de los servicios que presta "LA EMPRESA" a otras compañías, "EL TRABAJADOR" realizará todas y cada una de las actividades que le sean ordenadas para el cumplimiento de los compromisos que "LA EMPRESA" tenga o llegue a adquirir con tercero o terceros, reconociendo expresamente "EL TRABAJADOR" que dicha situación de ninguna manera lo vinculará laboralmente con las compañías a las cuales preste servicios "LA EMPRESA", ya que no estará sujeto a la subordinación de las mismas, ni recibirá remuneración alguna de ellas.',
    '<b>3.</b> Desde luego lo establecido anteriormente en esta cláusula es a propósito...',
    '<b>4.</b> El presente contrato de trabajo se celebra por el tiempo determinado empezando a surtir efectos...',
    '<b>5.</b> "EL TRABAJADOR" se compromete a prestar sus servicios en las instalaciones de "LA EMPRESA"...',
    '<b>6.</b> "LA EMPRESA" celebra el presente contrato fundada en la declaración II inciso a)...',
    '<b>7.</b> "LA EMPRESA le cubrirá "EL TRABAJADOR", por todos los servicios que proporcionará...',
    '<b>8.</b> La duración de la jornada semanal de trabajo será de 48 horas...',
    '<b>9.</b> Las partes convienen en que el día de descanso semanal será el domingo...',
    '<b>10.</b> "LA EMPRESA" le pagará a "EL TRABAJADOR" un aguinaldo...',
    '<b>11.</b> "EL TRABAJADOR" disfrutará anualmente de los días de vacaciones...',
    '<b>12.</b> Serán días de descanso obligatorio los que señala el Art. 74...',
    '<b>13.</b> "EL TRABAJADOR", durante su relación de trabajo, no prestará servicios...',
    '<b>14.</b> Queda prohibido a "EL TRABAJADOR" disponer para su beneficio particular...',
    '<b>15.</b> "EL TRABAJADOR" manifiesta saber y reconoce que su trabajo implica acceso...',
    '<b>16.</b> "EL TRABAJADOR" reconoce que son propiedad exclusiva de "LA EMPRESA"...',
    '<b>17.</b> Conforme a lo dispuesto por la fracción X del Artículo 134...',
    '<b>18.</b> Para todo lo dispuesto con riesgos de trabajo y enfermedades o accidentes...',
    '<b>19.</b> El trabajador se obliga a dar aviso de inmediato a "LA EMPRESA"...',
    '<b>20.</b> "LA EMPRESA" proporcionará capacitación y adiestramiento a "EL TRABAJADOR"...',
    '<b>21.</b> Sin perjuicio de cualquier disposición legal, este contrato se rescindirá...',
    '<b>22.</b> Queda estrictamente prohibido entablar una relación de carácter afectivo...',
    '<b>23.</b> Ambas partes convienen que, en lo no previsto por el presente contrato...',
    '<b>24.</b> Leído íntegramente el presente contrato y con conocimiento de su valor y fuerza legal, "EL TRABAJADOR" y el representante de "LA EMPRESA" la firman y ratifican de conformidad en la Ciudad de Tlajomulco de Zúñiga, Jalisco a {Diaactual}.'
];
